### Objective: Perform statistical analysis, manipulation, and visualization of a dataset using only Python and the NumPy library.

In [45]:
import numpy as np

#### Step 1: Load the data using NumPy script

In [64]:
data = np.genfromtxt('iris.csv', delimiter=',', dtype='str')
data

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [62]:
# separate numeric values and labels
features = data[:, :-1].astype(float) # Convert numeric columns to float
labels = data[:, -1] # Extract labels (last column)

print("Features:\n", features[:5])      # Display first 5 rows of numeric data
print("Labels:\n", labels[:5])          # Display first 5 labels

Features:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Labels:
 ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


### Step 2: Data Cleaning

1. Check for missing values and handle them (e.g., replacing with the mean of the column).
2. Normalize the data for better comparisons.

In [87]:
# Check for missing values
missing = np.isnan(features)

if np.any(missing):
    print('Missing value detected!')

# Replace missing values with the column mean
col_means = np.nanmean(features, axis = 0)
features = np.where(missing, col_means, features)

# Normalize the features (Min-Max scaling)
min_vals = np.min(features, axis=0)
max_vals = np.max(features, axis=0)

normalized_features = (features - min_vals) / (max_vals - min_vals)
print('Normalized Features : \n', normalized_features[:5])

Normalized Features : 
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


### Step 3: Statistical Analysis
1. Calculate basic statistics (mean, median, standard deviation, etc.).
2. Derive insights, such as correlation between features.

In [92]:
# Statistical measures

mean = np.mean(normalized_features, axis=0)
median = np.median(normalized_features, axis=0)
std_devs = np.std(normalized_features, axis=0)

# Correlation matrix
correlation_matrix = np.corrcoef(normalized_features.T)

print('Mean of each features : \n', mean)
print('Correlation Matrix : \n', correlation_matrix)

Mean of each features : 
 [0.4287037  0.43916667 0.46757062 0.45777778]
Correlation Matrix : 
 [[ 1.         -0.10936925  0.87175416  0.81795363]
 [-0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.81795363 -0.35654409  0.9627571   1.        ]]


### Step 4: Visualization using ASCII-style visualizations:

In [101]:
def ascii_histogram(data, bins=10):
    hist, bin_edges = np.histogram(data, bins=bins)
    for i, count in enumerate(hist):
        print(f"{bin_edges[i]:.2f} - {bin_edges[i+1]:.2f} | {'#' * count}")

print('Histogram of the first feature : ')
ascii_histogram(normalized_features[:, 0])

Histogram of the first feature : 
0.00 - 0.10 | #########
0.10 - 0.20 | #######################
0.20 - 0.30 | ##############
0.30 - 0.40 | ###########################
0.40 - 0.50 | ######################
0.50 - 0.60 | ####################
0.60 - 0.70 | ##################
0.70 - 0.80 | ######
0.80 - 0.90 | #####
0.90 - 1.00 | ######


### Step 5: Linear Algebra Applications
Solve a small system of linear equations related to the dataset for practice: 𝐴𝑥 = 𝐵

In [107]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
x = np.linalg.solve(A, B)
print('Solution to Ax = B : ', x)

Solution to Ax = B :  [-4.   4.5]


### Step 6: Save the cleaned and normalized dataset:

In [116]:
np.savetxt('processed_iris.csv', normalized_features, delimiter=',')